### PR TITLE
Update upc_keys.c

### PR DESCRIPTION
**Pull request by SeDi343**
Added line in void usage for better prefix description

### CODE REVIEW

**Comment by spaze** [comment]
Thanks. `upc_keys.c` does not work for Ubee so you might want to remove that, also please change the commit message and pull request title to something more meaningful.

**Comment by SeDi343** [comment]
But why are websites link their website to this GitHub project and this c file, if they support Ubee?

**Comment by spaze** [comment]
You'd have to ask the website owners. But if you're talking about my site, https://upc.michalspacek.cz/, it says

> Uses [modified `upc_keys.c`](https://github.com/spaze/upc_keys-lambda) originally by [Peter "blasty" Geissler](https://haxx.in/). [Ubee passwords](https://ubee.deadcode.me/) by Dušan Klinec & Miroslav Svítok, `0xDEADC0DE`. Thanks!

**Comment by SeDi343** [comment]
Supported routers: Technicolor TC7200 (serial number prefix SAAP, SAPP, SBAP), Ubee EVW3226 (serial number prefix UAAP)  so the code should also work with Ubee routers!?

**Comment by spaze** [comment]
No, it doesn't work with Ubee. The *site* supports TC7200 and EVW3226. For TC7200 it uses this code, for EVW3226 it uses a different database, see my previous comment.

**Pull request closed without merging**
